{% set name = "felyxcontribs-metrics-base" %}
{% set version = "1.0.3" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.ifremer.fr/felyx/felyxcontribs_metrics_base/-/archive/{{ version }}/felyxcontribs_metrics_base-{{ version }}.tar.gz
  sha256: bd3a2da174eaafb20ea1ca632b4ae03406f2ccb0564d

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - python >={{ python_min }}
    - pip
    - poetry-core
    - poetry-dynamic-versioning

  run:
    - python >={{ python_min }}
    - virtualenv >=20.13.3,<20.14
    
test:
  requires:
    - python {{ python_min }}
  imports:
    - felyxcontribs_metrics_base

about:
  home: https://gitlab.ifremer.fr/felyx/felyxcontribs_metrics_base
  license: LGPL-3.0-only
  license_file: LICENSE
  summary: felyx is a free software solution, written in python, whose aim is to provide Earth Observation data producers and users with an open-source, flexible and reusable tool to allow scientific analysis and performance monitoring of scientific observation data through subsetting over specific areas or matching up with in situ measurements.

extra:
  recipe-maintainers:
    - erwanbodere
    - cso2943
    - criou-cg
    - marie59
